baseURL = "http://sdaps.org/"
languageCode = "en-us"
title = "SDAPS"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

[params]
	# General information
	author = "Benjamin Berg"
	description = "Scripts for data acquisition with paper-based surveys."
	copyright = "Released under GPLv3+/LPPLv1.3c+"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/sdaps/sdaps"

	version = "1.9.2"
	logo = "images/sdaps.png"
	favicon = "images/sdaps.svg"

    custom_css = ['fa/css/all.css']

	[params.palette]
    	primary = "teal"
    	accent  = "orange"

[social]
	github  = "sdaps"
    email = "benjamin@sipsolutions.net"
    matrix = "https://matrix.to/#/!ycTzzbwRIINFSJQltE:matrix.org"
    irc = "freenode.net/sdaps"
    mailinglist = "https://dir.gmane.org/gmane.comp.statistics.sdaps"


[[menu.main]]
	pre    = "<i class='fas fa-sticky-note'></i> "
    name   = "Overview"
    url    = "/"
    weight = 10

[[menu.main]]
    pre    = "<i class='fas fa-clipboard-list'></i> "
    name   = "Getting started"
	url    = "getting-started/"
	weight = 20

[[menu.main]]
    pre    = "<i class='fas fa-users'></i> "
	name   = "Contribute"
	url    = "contribute/"
	weight = 30

[[menu.main]]
	pre    = "<i class='fas fa-newspaper'></i> "
    name   = "News"
	url    = "news/"
	weight = 40

[[menu.main]]
	pre    = "<i class='fas fa-book'></i>"
	name   = "Documentation"
	url	   = "documentation/"
	weight = 50

[[menu.main]]
	pre	   = "<i class='fas fa-handshake'></i> "
	name   = "Used by"
	url    = "used-by/"
	weight = 60

[[menu.main]]
	pre	   = "<i class='fas fa-bullseye'></i> "
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 70

[[menu.main]]
	name   = "Imprint"
	url    = "imprint/"
	pre    = "<i class='far fa-address-card'></i>"
	weight = 200

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
    plainIDAnchors = true
